name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Set up Maven settings.xml
      run: |
        mkdir -p $HOME/.m2
        echo "<settings xmlns=\"http://maven.apache.org/SETTINGS/1.0.0\"
              xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"
              xsi:schemaLocation=\"http://maven.apache.org/SETTINGS/1.0.0
                                  http://maven.apache.org/xsd/settings-1.0.0.xsd\">
          <servers>
              <server>
                  <id>nexus</id>
                  <username>\${env.NEXUS_USERNAME}</username>
                  <password>\${env.NEXUS_PASSWORD}</password>
              </server>
          </servers>
        </settings>" > $HOME/.m2/settings.xml
      env:
        NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
        NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}

    - name: Print settings.xml for debugging
      run: cat $HOME/.m2/settings.xml

    - name: Build with Maven
      run: mvn clean install

    - name: Deploy to Nexus
      run: mvn deploy
      env:
        NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
        NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
